# Using the official Debian 13 (Trixie) image
FROM debian:trixie

# Disabling interactive apt dialogs
ENV DEBIAN_FRONTEND=noninteractive

# Connect contrib/non-free and install packages for building
RUN sed -i 's/Components: main/Components: main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y \
    build-essential gfortran git ccache checkinstall pkg-config \
    tar zip unzip rsync cpio alien patchelf file gettext \
    curl wget vim-tiny locales mc \
    rustc cargo golang-go ruby ruby-dev \
    zstd libzstd-dev \
    openssl libssl-dev gnupg libssh-dev libssh2-1-dev libncurses-dev \
    perl perl-modules \
    python3 python3-dev python3-setuptools python3-mako python3-wheel \
    python3-build python3-installer python3-editables python3-pluggy \
    python3-poetry-core flit python3-maturin \
    python3-hatchling python3-hatch-vcs python3-hatch-fancy-pypi-readme python3-hatch-requirements-txt \
    python3-setuptools-scm python3-scikit-build-core \
    autoconf automake libtool autopoint cmake meson ninja-build \
    libx11-dev libxext-dev libxcomposite-dev libxinerama-dev \
    libxrandr-dev libxrender-dev libxft-dev libxtst-dev libxss-dev \
    libxpresent-dev xserver-xorg-dev libxdamage-dev libxi-dev \
    libwayland-dev wayland-protocols libxkbcommon-dev \
    libimlib2-dev libpango1.0-dev libglib2.0-dev tk-dev liblua5.4-dev \
    libjpeg-dev libpng-dev libgif-dev libreadline-dev libgtk-3-dev \
    libgl-dev mesa-common-dev libglu-dev osspd \
    libegl1-mesa-dev libgles2-mesa-dev \
    libsndfile1-dev libpulse-dev libasound2-dev libdbus-1-dev && \
    apt-get install -y --no-install-recommends asciidoc-base intltool xmlto && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/vim vim /usr/bin/vim.tiny 10

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENV EDITOR=vim
ENV VISUAL=vim

# Enable ccache to speed up C/C++ rebuilds
ENV PATH="/usr/lib/ccache:$PATH"

# Allow pip to install packages globally within an isolated container
ENV PIP_BREAK_SYSTEM_PACKAGES=1

WORKDIR /build
